import { CaptionPreset } from '../types';

export const CAPTION_PRESETS: CaptionPreset[] = [
  {
    id: 'side-by-side',
    name: 'Side-by-Side',
    style: {
      fontSize: 36,
      color: '#ffffff',
      glow: false,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 3,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 10,
      fontWeight: '800',
      isDynamic: true,
      threeColors: ['#ffffff', '#ffff00'],
      isSmart: true
    },
    animation: 'typewriter'
  },
  {
    id: 'viral-ai-smart',
    name: 'Viral AI Smart',
    style: {
      fontSize: 72,
      color: '#ffffff',
      glow: false,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 12,
      fontWeight: '800',
      isDynamic: true,
      threeColors: ['#ffff00', '#ffffff', '#00ff00'],
      isSmart: true
    },
    animation: 'pop'
  },
  {
    id: 'hormozi-bold',
    name: 'Hormozi Bold',
    style: {
      fontSize: 80,
      color: '#ffff00',
      glow: false,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 13,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'pop'
  },
  {
    id: 'neon-storyteller',
    name: 'Neon Storyteller',
    style: {
      fontSize: 48,
      color: '#00ffff',
      glow: true,
      border: 'thin',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'original',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: 'rgba(0,255,255,0.5)',
      strokeWidth: 4,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'glow'
  },
  {
    id: 'minimalist-pro',
    name: 'Minimalist Pro',
    style: {
      fontSize: 48,
      color: '#ffffff',
      glow: false,
      border: 'none',
      font: 'Inter',
      position: 'bottom',
      backgroundColor: 'transparent',
      case: 'original',
      wordsPerLine: 6,
      shadow: true,
      shadowColor: 'rgba(0,0,0,0.5)',
      strokeWidth: 0,
      fontWeight: '600',
      letterSpacing: '0.02em'
    },
    animation: 'typewriter'
  },
  {
    id: 'gaming-burst',
    name: 'Gaming Burst',
    style: {
      fontSize: 60,
      color: '#ff00ff',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#ffffff',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 10,
      fontWeight: '900',
      isDynamic: false
    },
    animation: 'typewriter'
  },
  {
    id: 'professional-viral',
    name: 'Professional Viral',
    style: {
      fontSize: 72,
      color: '#ffffff',
      glow: false,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 12,
      fontWeight: '800',
      isDynamic: true
    },
    animation: 'typewriter'
  },
  {
    id: 'professional-three-color',
    name: 'Viral 3-Color',
    style: {
      fontSize: 72,
      color: '#ffffff',
      glow: false,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 12,
      fontWeight: '800',
      isDynamic: true,
      threeColors: ['#ffff00', '#ffffff', '#00ff00']
    },
    animation: 'typewriter'
  },
  {
    id: 'viral-yellow-pro',
    name: 'Viral Yellow (Pro)',
    style: {
      fontSize: 72,
      color: '#ffff00',
      glow: false,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 12,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'typewriter'
  },
  {
    id: 'zeemo-pro',
    name: 'Zeemo Pro',
    style: {
      fontSize: 64,
      color: '#ffffff',
      glow: false,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 6,
      letterSpacing: '0.05em',
      italic: true,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'typewriter'
  },
  {
    id: 'kinetic-stacking',
    name: 'Kinetic Stacking',
    style: {
      fontSize: 48,
      color: '#ffffff',
      glow: false,
      border: 'none',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      case: 'uppercase',
      wordsPerLine: 4,
      shadow: true,
      shadowColor: 'rgba(0,0,0,0.8)',
      strokeWidth: 0,
      fontWeight: '800'
    },
    animation: 'pop'
  },
  {
    id: 'hindi-viral-yellow',
    name: 'Hindi Viral Yellow',
    style: {
      fontSize: 52,
      color: '#ffff00',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'bottom',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 2,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 6,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'pop'
  },
  {
    id: 'hindi-neon-green',
    name: 'Hindi Neon Green',
    style: {
      fontSize: 48,
      color: '#00ff00',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'bottom',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 2,
      shadow: true,
      shadowColor: 'rgba(0,0,0,0.8)',
      strokeWidth: 8,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'glow'
  },
  {
    id: 'karaoke-blue',
    name: 'Karaoke Blue',
    style: {
      fontSize: 40,
      color: '#ffffff',
      glow: false,
      border: 'thick',
      font: 'Inter',
      position: 'bottom',
      backgroundColor: 'rgba(0,0,0,0.5)',
      outlineColor: '#3b82f6',
      case: 'original',
      wordsPerLine: 5,
      shadow: true,
      shadowColor: 'rgba(0,0,0,0.8)',
      strokeWidth: 4,
      fontWeight: '800'
    },
    animation: 'pop'
  },
  {
    id: 'typewriter-white',
    name: 'Typewriter White',
    style: {
      fontSize: 44,
      color: '#ffffff',
      glow: false,
      border: 'none',
      font: 'Courier New',
      position: 'bottom',
      backgroundColor: 'transparent',
      case: 'original',
      wordsPerLine: 6,
      shadow: true,
      shadowColor: 'rgba(0,0,0,0.8)',
      strokeWidth: 0,
      fontWeight: '700'
    },
    animation: 'pop'
  },
  {
    id: 'hindi-shadow-white',
    name: 'Hindi Shadow White',
    style: {
      fontSize: 50,
      color: '#ffffff',
      glow: false,
      border: 'none',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 0,
      fontWeight: '800'
    },
    animation: 'pop'
  },
  {
    id: 'hindi-gradient-cyan',
    name: 'Hindi Gradient Cyan',
    style: {
      fontSize: 46,
      color: '#00ffff',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#ff00ff',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: false,
      shadowColor: 'transparent',
      strokeWidth: 8,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'bounce'
  },
  {
    id: 'hindi-bold-red',
    name: 'Hindi Bold Red',
    style: {
      fontSize: 54,
      color: '#ff0000',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#ffffff',
      case: 'uppercase',
      wordsPerLine: 2,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 10,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'pop'
  },
  {
    id: 'hindi-royal-gold',
    name: 'Hindi Royal Gold',
    style: {
      fontSize: 48,
      color: '#ffd700',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 2,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 9,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'pop'
  },
  {
    id: 'hindi-soft-pink',
    name: 'Hindi Soft Pink',
    style: {
      fontSize: 44,
      color: '#ff69b4',
      glow: true,
      border: 'thin',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: 'rgba(255,105,180,0.5)',
      strokeWidth: 8,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'pop'
  },
  {
    id: 'hindi-classic-blue',
    name: 'Hindi Classic Blue',
    style: {
      fontSize: 46,
      color: '#1e90ff',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#ffffff',
      case: 'uppercase',
      wordsPerLine: 2,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 6,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'pop'
  },
  {
    id: 'beast-mode-orange',
    name: 'Viral Orange (Beast)',
    style: {
      fontSize: 72,
      color: '#ff6b00',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 11,
      fontWeight: '900',
      isDynamic: true
    },
    animation: 'pop'
  },
  {
    id: 'electric-green',
    name: 'Electric Green',
    style: {
      fontSize: 68,
      color: '#00ff00',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 9,
      fontWeight: '800',
      isDynamic: false
    },
    animation: 'snappy'
  },
  {
    id: 'modern-bold-clean',
    name: 'Modern Sans (Clean)',
    style: {
      fontSize: 64,
      color: '#ffffff',
      glow: false,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 2,
      shadow: true,
      shadowColor: 'rgba(0,0,0,0.4)',
      strokeWidth: 11,
      fontWeight: '900',
      isDynamic: false
    },
    animation: 'bounce'
  },
  {
    id: 'retro-glitch-white',
    name: 'Retro Glitch',
    style: {
      fontSize: 60,
      color: '#ffffff',
      glow: false,
      border: 'none',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#8B4513', // Mehandi (Saddle Brown)
      strokeWidth: 0,
      fontWeight: '900',
      isDynamic: false
    },
    animation: 'glitch'
  },
  {
    id: 'golden-spotlight',
    name: 'Golden Spotlight',
    style: {
      fontSize: 70,
      color: '#ffff00',
      glow: true,
      border: 'thick',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#b8860b',
      strokeWidth: 9,
      fontWeight: '800',
      isDynamic: true
    },
    animation: 'glow'
  },
  {
    id: 'long-video-pro',
    name: 'Long Video Pro',
    style: {
      fontSize: 32,
      color: '#ffff00',
      glow: false,
      border: 'none',
      font: 'Inter',
      position: 'bottom',
      backgroundColor: 'rgba(0,0,0,0.85)',
      outlineColor: '#000000',
      case: 'uppercase',
      wordsPerLine: 3,
      shadow: false,
      shadowColor: 'transparent',
      strokeWidth: 0,
      fontWeight: '900',
      isDynamic: true,
      threeColors: ['#ffff00', '#ffffff', '#00ff00'],
      isSmart: true,
      padding: '8px 16px',
      borderRadius: '8px'
    },
    animation: 'pop'
  },
  {
    id: 'adaptive-dynamic',
    name: 'Adaptive Dynamic',
    style: {
      color: '#ffffff',
      fontSize: 48,
      font: 'Rajdhani',
      position: 'bottom',
      backgroundColor: 'rgba(0,0,0,0.85)',
      padding: '12px 24px',
      borderRadius: '16px',
      case: 'original',
      border: 'none',
      wordsPerLine: 2,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 0,
      fontWeight: '900',
      isDynamic: true,
      threeColors: ['#ffffff', '#ffff00', '#00ff1a'],
      isSmart: true
    },
    animation: 'skate'
  },
  {
    id: 'triple-stroke-elite',
    name: 'Elite Triple Stroke',
    style: {
      fontSize: 24,
      color: '#ffffff',
      glow: false,
      border: 'none',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 4,
      fontWeight: '900',
      isDynamic: false,
      isSmart: true,
      tripleBorder: true,
      tripleBorderColors: ['#FFD700', '#0047AB', '#000000']
    },
    animation: 'typewriter'
  },
  {
    id: 'triple-stroke-royal-thin',
    name: 'Royal Triple Thin',
    style: {
      fontSize: 24,
      color: '#ffffff',
      glow: false,
      border: 'none',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 2,
      fontWeight: '900',
      isDynamic: false,
      isSmart: true,
      tripleBorder: true,
      tripleBorderColors: ['#1E90FF', '#FFD700', '#FF0000'] // Blue, Gold, Red
    },
    animation: 'typewriter'
  },
  {
    id: 'trinity-thin',
    name: 'Trinity Thin',
    style: {
      fontSize: 24,
      color: '#ffffff',
      glow: false,
      border: 'none',
      font: 'Inter',
      position: 'middle',
      backgroundColor: 'transparent',
      case: 'uppercase',
      wordsPerLine: 1,
      shadow: true,
      shadowColor: '#000000',
      strokeWidth: 1,
      fontWeight: '900',
      isDynamic: false,
      isSmart: true,
      tripleBorder: true,
      tripleBorderColors: ['#1E90FF', '#FFD700', '#FF0000']
    },
    animation: 'typewriter'
  }
];
